Feature footer
PipHarsveld/Hallo-Strandeiland pull request #25
Opened 2023-06-06 13:17 UTC by Inevdhoven

Footer toevoegen aan de main.

2023-06-06 14:02 UTC, PipHarsveld commented
Misschien is het handig als we bij de :root variable een naming structuur aanhouden zodat het overzichtelijk blijft.
Ik zat te denken aan --categorie-wat(-specificatie)
Waarbij:
categorie: color, border, font etc
wat: op welk deel is het van toepassing? background, text, tag, headers, paragraph etc
specificatie: niet altijd nodig maar bijv primary, secundary, bold, medium etc


Voorbeeld:
```
:root {
    --color-background: #F0F0EB;
    --color-text-primary: #1B1B1B;
    --color-text-secundairy: #B3B3B3;
    --color-tag-duurzaam: rgba(31, 195, 67, .5);

    --font-headers-medium: 'Poppins-Medium';
    --font-paragraph-medium: 'Poppins-Medium';
}
```


Is maar een idee maar het lijkt me wel handig om af te spreken hoe we dit gaan aanpakken. Lmk wat je hiervan vindt!

2023-06-06 14:02 UTC, PipHarsveld commented
Verder ziet het er netjes uit!! 😃

2023-06-06 14:10 UTC, PipHarsveld requested changes
Zelfde als bij de header:

Misschien is het handig als we bij de :root variable een naming structuur aanhouden zodat het overzichtelijk blijft.
Ik zat te denken aan --categorie-wat(-specificatie)
Waarbij:
categorie: color, border, font etc
wat: op welk deel is het van toepassing? background, text, tag, headers, paragraph etc
specificatie: niet altijd nodig maar bijv primary, secundary, bold, medium etc


Voorbeeld:
```
:root {
    --color-background: #F0F0EB;
    --color-text-primary: #1B1B1B;
    --color-text-secundairy: #B3B3B3;
    --color-tag-duurzaam: rgba(31, 195, 67, .5);

    --font-headers-medium: 'Poppins-Medium';
    --font-paragraph-medium: 'Poppins-Medium';
}
```


Is maar een idee maar het lijkt me wel handig om af te spreken hoe we dit gaan aanpakken. Lmk wat je hiervan vindt!

2023-06-07 06:50 UTC, Inevdhoven commented
Ik heb de variabelen ook in de footer aangepast, ik hoor graag wat je er van vind. :)

2023-06-07 19:37 UTC, PipHarsveld approved these changes
Looks good! :D

2023-06-08 07:23 UTC, merged